version: '3'
services:
  mono_vslam:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/mono_vslam_py_prototype
    working_dir: /mono_vslam_py_prototype
    ports:
      - 8000:8000

  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mono_vslam_sample
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asis/Tokyo'
    ports:
      - 3306:3306
